version: '3.7'
services:
  application:
    build:
      context: .
    environment:
      - filepath=${filepath}
      - charToCount=${charToCount}
    volumes:
      - $PWD/src/main/resources/mount:/Users/alyssaandrade/IdeaProjects/Docs
      #/usr/local/application-resources
